services:
  backend:
    build:
      context: ./src
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
    environment:
      DATABASE_URL: mysql+pymysql://root:root@database/sistema_vendas
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000"]
    depends_on:
      database:
        condition: service_healthy
      
  tests:
    build:
      context: ./src
    volumes:   
      - ./src:/app
    environment:
      - PYTHONPATH=/app
    command: ["pytest", "--disable-warnings", "-v"]
    depends_on:
      - backend

  lint:
    build: 
      context: ./src
    volumes:
      - ./src:/app
    environment:
      - PYTHONPATH=/app
    command: ["pylint", "--disable=R,C", "."]

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  database:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema_vendas
    ports:
      - "3306:3306"
    volumes:
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - database
